[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = ['bun run build']

[start]
cmd = 'bunx serve -s build'

[variables]
NIXPACKS_PATH = "/app"
CI = "false"