[phases.setup]
nixPkgs = ['bun']

[phases.install]
cmds = ['bun install']

[phases.build]
cmds = []

[start]
cmd = 'bun run index.js'

[variables]
NIXPACKS_PATH = "/app"
CI = "false"
PORT = "8080"
NODE_ENV = "production"